### ISSUE TITLE
Mission 4 - SDS: Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [batz91/Tlushi#18]
מה עם תכנית בדיקות?

**Comment by batz91** [comment]
@kob-e היה רשום שזה רשות, בכל מקרה רשמנו עכשיו את תוכנית הבדיקות.
אם אפשר לבדוק שוב ולקבל feedback גם על משימה 3.
תודה וחג שמח

**Comment by itai00** [comment]
@kob-e 

נשמח לדעת על מה ירדו לנו נקודות באס די אס כדי שנוכל לתקן אותם
תודה.
